commerce_canadapost.settings:
  type: config_object
  label: 'Canada Post API settings'
  mapping:
    api:
      type: mapping
      label: 'Information required for connecting to the API'
      mapping:
        customer_number:
          type: string
          label: 'Customer number'
        username:
          type: string
          label: 'Username'
        password:
          type: string
          label: 'Password'
        rate:
          type: mapping
          label: 'Ratings API settings'
          mapping:
            origin_postal_code:
              type: string
              label: 'Origin postal code'
        shipping_rates:
          type: mapping
          label: 'Shipping Rates'
          mapping:
            modifier:
              type: string
              label: 'Modifier'
            amount:
              type: commerce_number
              label: 'Amount'
